[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.0.0"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"
  PRISMA_SKIP_POSTINSTALL_GENERATE = "true"

# Next.js plugin with Prisma support
[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    enableNextJsLink = true

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
